spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring-jpa
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true